DROP TABLE IF EXISTS `wp_wpdevart_reservations`;
CREATE TABLE `wp_wpdevart_reservations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `calendar_id` int(11) NOT NULL,
  `single_day` varchar(16) NOT NULL,
  `check_in` varchar(16) NOT NULL,
  `check_out` varchar(16) NOT NULL,
  `start_hour` varchar(16) NOT NULL,
  `end_hour` varchar(16) NOT NULL,
  `currency` varchar(32) NOT NULL,
  `count_item` int(10) NOT NULL,
  `price` float NOT NULL,
  `total_price` float NOT NULL,
  `extras` text NOT NULL,
  `extras_price` float NOT NULL,
  `form` text NOT NULL,
  `address_billing` text NOT NULL,
  `address_shipping` text NOT NULL,
  `email` varchar(128) NOT NULL,
  `status` varchar(16) NOT NULL,
  `payment_method` varchar(32) NOT NULL,
  `payment_status` varchar(32) NOT NULL,
  `date_created` varchar(64) NOT NULL,
  `is_new` int(1) NOT NULL,
  `sale_percent` varchar(16) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
